Set wshShell = wscript.CreateObject("WScript.Shell")
m = msgbox ("Deseja ocultar arquivos?"&vbCRLF&"[AVISO, O PROCESSO NÃO PODERÁ SER INTERROMPIDO, SCRIPT DE TESTE, PODE APAGAR SEUS ARQUIVOS ACIDENTALMENTE, SIGA AS INSTRUÇÕES A RISCA]!", 36 ,"OCULTADOR DE ARQUIVOS - JANELA DE OPÇÕES")
WshShell.Run "OCCRYPT.BAT " & m
